server:
  port: 7710

spring:
  profiles:
    active: dev
#    active: prod
  cloud:
    gateway:
      routes:
      - id:
        uri:
        predicates:
        - name: Cookie
          args:
            name: mycookie
            regexp: mycookievalue